pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'Charlie Cheng的网站'
   keywords: 'Charlie'
   description: '作者：Charlie'
  # home config
  en-us:
   title: 'Backyard of Charlie Cheng'
   keywords: 'Charlie'
   description: 'Author: Charlie'
 community:
  # 社区页配置
  zh-cn:
   title: '社区'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'page title'
   keywords: 'keyword1,keyword2'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'page title'
   keywords: 'keyword1,keyword2'
   description: 'page description'