pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: '查理的后花园'
   keywords: 'Charlie'
   description: '作者：Charlie'
  # home config
  en-us:
   title: 'Charlie Cheng Backyard'
   keywords: 'Charlie'
   description: 'Author: Charlie'
 community:
  # 社区页配置
  zh-cn:
   title: '社区'
   keywords: '最新动态，联系方式'
   description: '我的最新动态以及如何能够快速联系我'
  # community page config
  en-us:
   title: 'Community'
   keywords: 'Latest updates,Contact'
   description: 'My latest updates as well as contact information'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客'
   keywords: '个人文章汇总'
   description: '关于我对生活的看法'
  en-us:
   # blog list page config
   title: 'Blog'
   keywords: 'Collection of my articles'
   description: 'About my interpretation of life'